# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd5d52dd28cb8790c11fc4c0e69f1ee9f5e4ae6a8ff6abcc5e3e3789c53f69aa8a3e611c8e3d66083357a31d849126e94cababdf22edd91b677eab86e93e619d

test:
  secret_key_base: 9bf0b1db21c485478d13b525372e4e9da4783e2dc3b545183190edbfa576570508b82aa68c298aec730d9da750ad4abf7d28348809392f20d4652ca363ea06d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
